### ISSUE TITLE
alias-model-in-controller throws TypeError: Cannot read property 'forEach' of undefined if mixin is added to the controller

### ISSUE THREAD

**Issue by RafLeszczynski** [netguru/eslint-plugin-netguru-ember#1]
This is the route cause of a problem:
https://github.com/netguru/eslint-plugin-netguru-ember/blob/master/rules/alias-model-in-controller.js#L23

If mixin is added to the Controller `node.arguments[0]` points to mixin which type is `Identifier` not `ObjectExpression` and it doesn't have `properties`. 

```
Cannot read property 'forEach' of undefined
TypeError: Cannot read property 'forEach' of undefined
    at EventEmitter.CallExpression (/Users/rafal.leszczynski/Documents/airhelp-projects/ah-webapp/frontend/node_modules/eslint-plugin-netguru-ember/rules/alias-model-in-controller.js:33:17)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (/Users/rafal.leszczynski/Documents/airhelp-projects/ah-webapp/frontend/node_modules/eslint/lib/util/node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (/Users/rafal.leszczynski/Documents/airhelp-projects/ah-webapp/frontend/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:607:23)
    at CommentEventGenerator.enterNode (/Users/rafal.leszczynski/Documents/airhelp-projects/ah-webapp/frontend/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
    at Controller.traverser.traverse.enter (/Users/rafal.leszczynski/Documents/airhelp-projects/ah-webapp/frontend/node_modules/eslint/lib/eslint.js:905:36)
    at Controller.__execute (/Users/rafal.leszczynski/Documents/airhelp-projects/ah-webapp/frontend/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/Users/rafal.leszczynski/Documents/airhelp-projects/ah-webapp/frontend/node_modules/eslint/node_modules/estraverse/estraverse.js:501:28)
    at Controller.Traverser.controller.traverse (/Users/rafal.leszczynski/Documents/airhelp-projects/ah-webapp/frontend/node_modules/eslint/lib/util/traverser.js:36:33)

```

**Proposed solutions:**

Option A
There could be multiple mixins but the last `node` in `node.arguments` should always be `ObjectExpression` which contains `properties`. So we could do something this:

```JS
var properties = node.arguments[node.arguments.length - 1].properties;
```

Option B
Instead of counting for the last `node` in `node.arguments` array to be `ObjectExpression` we could filter this array like this:

```JS
var objectExpressionNodes = node.arguments.filter(function(argument) {
        return utils.isObjectExpression(argument);
});
      
var properties = objectExpressionNodes[0].properties;
```
 
What do you think about this proposals? I'm happy to make a PR with the fix. 

BTW I've encounter issues with `query-params-on-top`,  `order-in-components`, `named-functions-in-promises` and `routes-segments-snake-case`. Some of them could have similar route cause. Will investigate soon.

**Comment by RafLeszczynski** [comment]
another option could be to use this `findNodes` utils helper: https://github.com/netguru/eslint-plugin-netguru-ember/blob/master/rules/utils/utils.js#L21

**Comment by RafLeszczynski** [comment]
From what I see, the same pattern is used in `query-params-on-top`, `order-in-components` and `order-in-models` so in case of mixins there will be the same errors.

**Comment by michalsnik** [comment]
Hi @RafLeszczynski, thanks for pointing this out! I really appreciate it.
I definitely had to forget about mixins scenarios.

I like all of your propositions but I think that we should add a new method in `ember`, for example `getModuleProperties` and make use of `findNodes` inside of it, like so:
```javascript
function getModuleProperties(module) {
  return utils.findNodes(module.arguments, 'ObjectExpression')[0];
}
```

Then we'll be able to use it in example rule:
```javascript
var properties = ember.getModuleProperties(node);
```

As you say there are other rules that has the same issue with mixins, so putting it in nice function will increase readability and consistency.

What do you think about this implementation?

If you'd like please create PR, and don't forget about adding new test cases. I'd be happy to review this fix.

**Comment by RafLeszczynski** [comment]
👍 for the idea. I'll try to prepare PR today or tomorrow.

**Comment by michalsnik** [comment]
Great, thank you @RafLeszczynski ! Looking forward :)

**Comment by RafLeszczynski** [comment]
@michalsnik the PR is ready

**Comment by michalsnik** [comment]
I released version `0.0.5` with your fix. It seems to be working fine 👍

**Comment by RafLeszczynski** [comment]
@michalsnik as this is fixed, could you please close it?

**Comment by michalsnik** [comment]
Sure
